import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  isAuthenticated: false,
  isLoading: true,
  user: {
    fullName: "",
    email: "",
    phone: "",
    role: "",
    avatar: "",
    previewAvatar: "",
  },
};

export const accountSlice = createSlice({
  name: "account",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    doLoginAction: (state, action) => {
      state.isAuthenticated = true;
      state.user = action.payload;
      state.previewAvatar = action.payload?.avatar;
      state.isLoading = false;
    },
    doGetAccountAction: (state, action) => {
      state.isAuthenticated = true;
      state.user = action.payload;
      state.previewAvatar = action.payload?.avatar;
      state.isLoading = false;
    },
    doLogoutAction: (state, action) => {
      localStorage.removeItem("access_token");
      state.isAuthenticated = false;
      state.user = {
        fullName: "",
        email: "",
        phone: "",
        role: "",
        avatar: "",
        previewAvatar: "",
      };
    },
    doSetPreviewAvatar: (state, action) => {
      state.previewAvatar = action.payload;
    },
    doUpdateUserInfo: (state, action) => {
      state.user.fullName = action.payload.fullName;
      state.user.avatar = action.payload.avatar;
      state.user.phone = action.payload.phone;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {},
});

export const {
  doLoginAction,
  doGetAccountAction,
  doLogoutAction,
  doSetPreviewAvatar,
  doUpdateUserInfo,
} = accountSlice.actions;

export default accountSlice.reducer;
